[DEFAULT]
ignoreip = 127.0.0.1 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
banaction = iptables-allports
bantime   = 86400 ; 1 giorno
findtime  = 3600  ; 30 minuti
maxretry = 3

sender = gmmg.lan@gmx.it
destemail = fail2ban

#action = %(action_)s
action   = %(action_mwl)s

# logs override
#apache_error_log = /var/log/apache2/*error*log
#apache_access_log = /var/log/apache2/*access*log
#apache_error_log = /var/log/httpd/*error*log
#apache_access_log = /var/log/httpd/*access*log
nginx_access_log = /opt/npm/data/npm/logs/proxy-host-*_access.log 
nginx_error_log = /opt/npm/data/npm/logs/proxy-host-*_error.log 

[recidive]
enabled  = true
logpath  = /var/log/fail2ban.log
protocol = all
bantime  = 2592000 ; 1 month
findtime = 604800 ; 1 settimana
maxretry = 10

[sshd]
#enabled = true
maxretry = 3
port = 62228
action  = %(action_mwl)s
          %(action_abuseipdb)s[abuseipdb_apikey="a892181a0e3f4a57a78cc0b3aabb9739e791eac339606dfbcc0cd85b367eff8b9f2325dccc1ae18b", abuseipdb_category="18,22"]

[asterisk]
enabled = true
logpath  = /var/log/asterisk/full
 
[freepbx]
enabled = true
logpath  = /var/log/asterisk/freepbx_security.log

[nginx-http-auth]
#enabled = true

# To use 'nginx-limit-req' jail you should have `ngx_http_limit_req_module`
# and define `limit_req` and `limit_req_zone` as described in nginx documentation
# http://nginx.org/en/docs/http/ngx_http_limit_req_module.html
# or for example see in 'config/filter.d/nginx-limit-req.conf'
[nginx-limit-req]
#enabled = true

[nginx-botsearch]
#enabled = true

[nextcloud]
#enabled = true
logpath = /opt/dockers/nextcloud/data/data/nextcloud.log

[postfix]
#enabled  = true
port     = smtp,2525
maxretry = 1
 
[postfix-sasl]
#enabled  = true
port     = smtp,2525
maxretry = 1

[apache-auth]
#enabled = true

[apache-badbots]
#enabled = true
bantime  = 48h
maxretry = 1

[apache-noscript]
#enabled = true

[apache-overflows]
#enabled = true
maxretry = 2

[apache-nohome]
#enabled = true
maxretry = 2

[apache-botsearch]
#enabled = true
maxretry = 2

[apache-fakegooglebot]
#enabled = true
maxretry = 1
ignorecommand = %(ignorecommands_dir)s/apache-fakegooglebot <ip>

[apache-modsecurity]
#enabled = true
maxretry = 2

[apache-shellshock]
#enabled = true
maxretry = 1

[openvpn]
#enabled  = true
port     = 855
protocol = udp
logpath  = /var/log/openvpn/server.log

[wordpress-hard]
#enabled = true
logpath = /var/log/auth.log
maxretry = 1

[wordpress-soft]
#enabled = true
logpath = /var/log/auth.log
maxretry = 3
